name: checkstyle
on: [pull_request, push]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run checkstyle
        run: java -jar checkstyle.jar -c google_checkstyle.xml . 
