name: checkstyle
on: [pull_request, push]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run checkstyle
        run: java -jar $CHECKSTYLE_ACTION_DIR/checkstyle.jar -c $CHECKSTYLE_ACTION_DIR/google_checkstyle.xml . 
