name: Run Gradle on every push
on: push
jobs:
  gradle:
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Execute Gradle build
      run: ./gradlew build
